- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: Install flatpak packages
  flatpak:
    name: "{{item}}"
    state: present
    method: system
  with_items:
    - com.valvesoftware.Steam
    - com.spotify.Client
    - org.godotengine.Godot

- name: Install dev packages
  dnf:
    state: present
    name: ['clang', 'clang-devel', 'llvm', 'llvm-devel', 'cmake', 'gcc-c++',
  'make', 'python3-devel', 'zsh', 'java-1.8.0-openjdk-devel', 'java-11-openjdk-devel', 'SDL2-devel', 'glew-devel']

- name: Install applications
  dnf:
    state: present
    name: ['emacs', 'vim-X11', 'vim-powerline', 'irssi', 'terminator', 'pass', 'moc']

- name: Install window manager and dependencies
  dnf:
    state: present
    name: ['i3', 'i3lock', 'i3status', 'i3-doc', 'powerline', 'powerline-fonts',
  'fontawesome-fonts', 'arc-theme', 'playerctl']
